apiVersion: v2
name: azure-devops-agent
description: Dockerized Azure DevOps build agent on Kubernetes
type: application
version: 2.4.0
appVersion: "v2.4.0-vsts-v2.258.1"
keywords:
  - azure devops
  - build agent
  - dockerized agent
  - azure devops agent on kubernetes
  - azure devops agent
  - kubernetes
  - devops
home: "https://github.com/btungut/azure-devops-agent-on-kubernetes"
sources:
  - "https://github.com/btungut/azure-devops-agent-on-kubernetes"
maintainers:
  - name: "Burak Tungut"
    email: "info@buraktungut.com"
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: MIT
  artifacthub.io/links: |-
    - name: GitHub
      url: https://github.com/btungut/azure-devops-agent-on-kubernetes
